column_width = 120
indent_width = 4
indent_type = "Spaces"
line_endings = "Unix"
quote_style = "AutoPreferDouble"
call_parentheses = "Always"
space_after_function_names = "Never"
collapse_simple_statement = "Never"
block_new_line_gaps = "Never"

[sort_requires]
enabled = true
