[package]
name = "dotset-bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotset = { path = "../../dev/dotset" }
git2 = "0.18"
clap = { version = "4.4", features = ["derive"] }
